-- Correspondent Agent & People Database Schema
-- Run this in your Supabase SQL editor after the base schema

-- ============================================================
-- PEOPLE DATABASE
-- The foundation for Circles of Care and Correspondent context
-- ============================================================

CREATE TABLE people (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,

  -- Core Identity
  name TEXT NOT NULL,
  nickname TEXT,
  email TEXT[],
  phone TEXT[],
  address TEXT,
  photo TEXT, -- storage reference

  -- Relationship Mapping
  circle TEXT NOT NULL CHECK (circle IN (
    'family', 'neighbor', 'friend', 'professional', 'community', 'acquaintance'
  )),
  closeness INTEGER NOT NULL CHECK (closeness >= 1 AND closeness <= 5),
  relationship TEXT NOT NULL, -- free text: mother, design partner, etc.
  how_we_met TEXT,
  shared_with UUID[], -- references other people records

  -- Care Practice
  last_contact TIMESTAMPTZ,
  contact_method TEXT, -- text, email, in_person, phone_call
  ideal_cadence TEXT CHECK (ideal_cadence IN (
    'weekly', 'biweekly', 'monthly', 'quarterly', 'seasonal', 'as_needed'
  )),
  next_touchpoint TEXT,
  touchpoint_date DATE,
  care_notes TEXT,

  -- Personal Context
  birthday DATE,
  location TEXT,
  occupation TEXT,
  interests TEXT[],
  dietary TEXT,
  communication_style TEXT,
  gift_ideas TEXT[],
  notes TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Interaction log: append-only record of all interactions
CREATE TABLE interaction_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,
  person_id UUID REFERENCES people(id) ON DELETE CASCADE NOT NULL,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  type TEXT NOT NULL CHECK (type IN (
    'email_sent', 'email_received', 'text', 'call', 'in_person', 'letter', 'gift'
  )),
  summary TEXT,
  sentiment TEXT CHECK (sentiment IN (
    'warm', 'neutral', 'tense', 'celebratory', 'supportive'
  )),
  auto_logged BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- CORRESPONDENT AGENT
-- Message processing, drafting, and decision queue
-- ============================================================

-- Raw inbound messages from all channels
CREATE TABLE correspondent_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,

  -- Source info
  channel TEXT NOT NULL CHECK (channel IN (
    'email', 'sms', 'slack', 'newsletter', 'social'
  )),
  external_id TEXT, -- gmail message id, etc. for dedup
  thread_id TEXT, -- for threading conversations

  -- Sender
  sender_email TEXT,
  sender_name TEXT,
  sender_phone TEXT,
  person_id UUID REFERENCES people(id), -- matched person, null if unknown

  -- Content
  subject TEXT,
  body TEXT NOT NULL,
  body_html TEXT,
  snippet TEXT, -- short preview
  attachments JSONB, -- [{name, mime_type, size, storage_ref}]

  -- Metadata
  received_at TIMESTAMPTZ NOT NULL,
  is_read BOOLEAN DEFAULT false,
  labels TEXT[], -- gmail labels, etc.

  -- Processing state
  processed BOOLEAN DEFAULT false,
  urgency INTEGER DEFAULT 0 CHECK (urgency >= 0 AND urgency <= 10),
  importance INTEGER DEFAULT 0 CHECK (importance >= 0 AND importance <= 10),
  triage_summary TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Drafts generated by the Correspondent
CREATE TABLE correspondent_drafts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,
  message_id UUID REFERENCES correspondent_messages(id) ON DELETE CASCADE NOT NULL,
  person_id UUID REFERENCES people(id),

  -- Draft content
  channel TEXT NOT NULL CHECK (channel IN ('email', 'sms', 'slack')),
  subject TEXT,
  body TEXT NOT NULL,
  draft_tier TEXT NOT NULL CHECK (draft_tier IN (
    'full_draft', 'quick_reply', 'batched_reply', 'no_reply'
  )),

  -- Context used for generation
  relationship_context TEXT, -- snapshot of person context used
  thread_context TEXT, -- conversation thread summary
  voice_notes TEXT, -- notes about tone/style choices

  -- Queue state
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'approved', 'edited', 'sent', 'skipped', 'deferred'
  )),
  skip_count INTEGER DEFAULT 0,
  queue_position INTEGER,

  -- Triage scores (inherited from message)
  urgency INTEGER DEFAULT 0,
  importance INTEGER DEFAULT 0,

  -- Editing
  edited_body TEXT, -- user's edited version, null if sent as-is
  sent_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Correspondent processing runs
CREATE TABLE correspondent_runs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN (
    'running', 'completed', 'failed'
  )),
  messages_ingested INTEGER DEFAULT 0,
  messages_processed INTEGER DEFAULT 0,
  drafts_generated INTEGER DEFAULT 0,
  error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Voice model training samples (sent messages for style learning)
CREATE TABLE voice_samples (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users NOT NULL,
  person_id UUID REFERENCES people(id),
  circle TEXT, -- cached circle for style segmentation
  channel TEXT NOT NULL,
  content TEXT NOT NULL,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Correspondent configuration
CREATE TABLE correspondent_config (
  user_id UUID PRIMARY KEY REFERENCES auth.users,

  -- Gmail config
  gmail_access_token TEXT,
  gmail_refresh_token TEXT,
  gmail_token_expiry TIMESTAMPTZ,
  gmail_last_history_id TEXT, -- for incremental sync
  gmail_connected BOOLEAN DEFAULT false,

  -- Processing config
  process_time TIME DEFAULT '03:00:00', -- when to run nightly pipeline
  timezone TEXT DEFAULT 'America/Los_Angeles',

  -- Alert config
  emergency_alerts_enabled BOOLEAN DEFAULT true,
  emergency_closeness_threshold INTEGER DEFAULT 2, -- alert for closeness <= this

  -- Excluded contacts
  excluded_emails TEXT[], -- never process these
  excluded_names TEXT[],

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_people_user_circle ON people(user_id, circle);
CREATE INDEX idx_people_user_closeness ON people(user_id, closeness);
CREATE INDEX idx_people_email ON people USING GIN(email);
CREATE INDEX idx_people_phone ON people USING GIN(phone);

CREATE INDEX idx_interaction_log_person ON interaction_log(person_id, date DESC);
CREATE INDEX idx_interaction_log_user ON interaction_log(user_id, date DESC);

CREATE INDEX idx_correspondent_messages_user ON correspondent_messages(user_id, received_at DESC);
CREATE INDEX idx_correspondent_messages_external ON correspondent_messages(user_id, external_id);
CREATE INDEX idx_correspondent_messages_person ON correspondent_messages(person_id);
CREATE INDEX idx_correspondent_messages_unprocessed ON correspondent_messages(user_id, processed) WHERE processed = false;

CREATE INDEX idx_correspondent_drafts_user_status ON correspondent_drafts(user_id, status);
CREATE INDEX idx_correspondent_drafts_queue ON correspondent_drafts(user_id, status, queue_position) WHERE status = 'pending';

CREATE INDEX idx_voice_samples_user_circle ON voice_samples(user_id, circle);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE interaction_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE correspondent_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE correspondent_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE correspondent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE correspondent_config ENABLE ROW LEVEL SECURITY;

-- People policies
CREATE POLICY "Users can view own people" ON people FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own people" ON people FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own people" ON people FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own people" ON people FOR DELETE USING (auth.uid() = user_id);

-- Interaction log policies
CREATE POLICY "Users can view own interaction log" ON interaction_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own interaction log" ON interaction_log FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Correspondent messages policies
CREATE POLICY "Users can view own messages" ON correspondent_messages FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own messages" ON correspondent_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own messages" ON correspondent_messages FOR UPDATE USING (auth.uid() = user_id);

-- Correspondent drafts policies
CREATE POLICY "Users can view own drafts" ON correspondent_drafts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own drafts" ON correspondent_drafts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own drafts" ON correspondent_drafts FOR UPDATE USING (auth.uid() = user_id);

-- Correspondent runs policies
CREATE POLICY "Users can view own runs" ON correspondent_runs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own runs" ON correspondent_runs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own runs" ON correspondent_runs FOR UPDATE USING (auth.uid() = user_id);

-- Voice samples policies
CREATE POLICY "Users can view own voice samples" ON voice_samples FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own voice samples" ON voice_samples FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Correspondent config policies
CREATE POLICY "Users can view own config" ON correspondent_config FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own config" ON correspondent_config FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own config" ON correspondent_config FOR UPDATE USING (auth.uid() = user_id);

-- ============================================================
-- TRIGGERS
-- ============================================================

CREATE TRIGGER update_people_updated_at BEFORE UPDATE ON people
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_correspondent_drafts_updated_at BEFORE UPDATE ON correspondent_drafts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_correspondent_config_updated_at BEFORE UPDATE ON correspondent_config
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
